### PR TITLE
fix: latest finalized query

### LINKED ISSUE #679: [cosmos] change query of getting last finalized block
bcd@bcd-chain-0-validators-0:~$ bcd q wasm contract-state smart bbnc1ghd753shjuwexxywmgs4xz7x2q732vcnkm6h2pyv9s6ah3hylvrqv7u2f2 '{"last_finalized_height": {}}'
data: 500979

### PR DESCRIPTION
**Pull request by Lazar955**
closes #679

### CODE REVIEW

File: bsn/cosmos/clientcontroller/consumer.go [hunk 1]
```diff
@@ -511,6 +509,43 @@ func (wc *CosmwasmConsumerController) QueryDelegations(ctx context.Context) (*Co
...
+	}
+
+	// Marshal the query message to JSON
+	queryMsgBytes, err := json.Marshal(queryMsg)
+	if err != nil {
+		return nil, fmt.Errorf("failed to marshal query message: %w", err)
+	}
+
+	// Query the smart contract state
+	dataFromContract, err := wc.QuerySmartContractState(ctx, wc.cfg.BtcFinalityContractAddress, string(queryMsgBytes))
```
Comment (gusin13) [inline bsn/cosmos/clientcontroller/consumer.go:524]: the contract currently gives us finalized+1 height

it returns the next height which should be finalized, does this affect anything in this code?

Comment (gusin13) [reply bsn/cosmos/clientcontroller/consumer.go:524]: @Lazar955 https://github.com/babylonlabs-io/cosmos-bsn-contracts/pull/348

**Review by gusin13 — APPROVED** [review]
lgtm 👍

File: bsn/cosmos/clientcontroller/consumer.go (hunk 1 above)
Comment (gusin13) [reply bsn/cosmos/clientcontroller/consumer.go:524]: do you need to rebuild the contracts in e2e? wondering why e2e didnt complain though about this?
